# Generated by Django 5.0.4 on 2024-05-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem_alter_menu_inventory_alter_menu_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
